INSERT INTO jobs (title, description, requirements, pages, deadline, salary, status, admin_id, created_at) VALUES 
('AI-Powered Chatbot Development', 'Develop an AI-powered chatbot for customer service using natural language processing.', 'Python, NLP, Machine Learning, API Integration', 15, '2025-06-15 00:00:00', 2200.00, 'open', 1, NOW()),
('Mobile Game Development', 'Develop a casual mobile game with in-app purchases and social features.', 'Unity or Unreal Engine, C#, Mobile Development, Game Design', 20, '2025-06-30 00:00:00', 3500.00, 'open', 1, NOW()),
('E-learning Platform Development', 'Build a complete e-learning platform with course management, user authentication, and payment processing.', 'PHP/Node.js, React/Vue.js, MySQL/MongoDB, Payment Gateway Integration', 25, '2025-06-25 00:00:00', 4000.00, 'open', 1, NOW()),
('Blockchain Smart Contract Development', 'Develop secure smart contracts for a decentralized finance application.', 'Solidity, Ethereum, Web3.js, Smart Contract Security', 15, '2025-06-18 00:00:00', 3200.00, 'open', 1, NOW()),
('Virtual Reality Experience Design', 'Design an immersive virtual reality experience for a museum exhibition.', 'Unity/Unreal, 3D Modeling, VR Development, UX Design', 18, '2025-06-20 00:00:00', 2800.00, 'open', 1, NOW()),
('Corporate Brand Identity Redesign', 'Redesign the complete brand identity for a financial services company.', 'Adobe Creative Suite, Brand Strategy, Logo Design, Style Guide Creation', 12, '2025-06-10 00:00:00', 1800.00, 'open', 1, NOW()),
('Summer Marketing Campaign Strategy', 'Create a comprehensive summer marketing campaign for a beach resort.', 'Marketing Strategy, Content Creation, Social Media, Analytics', 8, '2025-06-01 00:00:00', 850.00, 'open', 1, NOW()),
('Product Packaging Design', 'Design attractive and eco-friendly packaging for a new organic food product line.', 'Adobe Illustrator, Packaging Design, Sustainable Materials Knowledge', 5, '2025-06-12 00:00:00', 650.00, 'open', 1, NOW()),
('SEO Optimization Project', 'Improve search engine rankings for an e-commerce website through comprehensive SEO optimization.', 'SEO Best Practices, Google Analytics, Content Optimization, Backlink Strategy', 6, '2025-06-08 00:00:00', 750.00, 'open', 1, NOW()),
('Cryptocurrency Market Analysis', 'Analyze current cryptocurrency market trends and provide investment recommendations.', 'Financial Analysis, Cryptocurrency Knowledge, Market Research, Data Visualization', 7, '2025-06-05 00:00:00', 550.00, 'open', 1, NOW()); 